version: "3.9"

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=liink
    command: mix do deps.get, deps.compile, ecto.create, ecto.migrate, phx.server
    volumes:
      - .:/opt/

  test:
    build: .
    depends_on:
      - db
    command: mix do deps.get --only, coveralls --trace --color
    environment:
      - MIX_ENV=test
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=liink-test
    volumes:
      - .:/opt/

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

