version: "3.9"

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=liink
    command: mix do deps.get, deps.compile, phx.server

  test:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=liink
    command: mix do deps.get, deps.compile, test

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5423:5432"
