#!/bin/bash
cd `git rev-parse --show-toplevel`
mix format mix.exs "lib/**/*.{ex,exs}" "test/**/*.{ex,exs}" --check-formatted && mix credo
if [ $? == 1 ]; then
   echo "commit failed due to format issues..."
   exit 1
fi
